# Nombre de la app:
spring.application.name = login

# Puerto del servidor:
server.port = 8091

# Configuración MySQL:
# Reemplazar ${DB_USER} por tu usuario y ${DB_PASSWORD} por tu contraseña de Mysql
spring.datasource.url = jdbc:mysql://localhost:3306/login_grupo3?serverTimezone=UTC
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# Configuración Hibernate:
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

# Configuración de Mailtrap:
# Esto permite que Spring se conecte a ese servidor para enviar los emails
spring.mail.host = smtp.mailtrap.io
spring.mail.port = 2525
spring.mail.username = b58ff381114de8
spring.mail.password = 8257a068155dcf
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

# Permite ver el detalle del error en la respuesta HTTP en Postman
server.error.include-message = always
